version: "3.8"
services:

  db:
    container_name: pg_intro_container
    image: postgres:15.0
    restart: always
    volumes:
      - ./postgres_intro_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432

#  pgadmin:
#    container_name: pgadmin4_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "80:80"

volumes:
  postgres_intro_data:
    name: postgres_intro_data